/* The contents of this file are NOT included in files generated by the html5 boilerplate build script */

/* Setup server API mocking with mockJax https://github.com/appendto/jquery-mockjax */
$.mockjax({
  url: '/restful/fortune',
  responseTime: 750,
  responseText: {
    status: 'success',
    fortune: 'Are you a turtle?'
  }
});